import { io } from "socket.io-client";
const URL = "http://localhost:3003";
const conn = () => new Promise((res) => { const s = io(URL, {transports:["polling"]}); s.on("connect",()=>res(s)); });
const emit = (s,ev,arg) => new Promise((res)=>s.emit(ev,arg,(r)=>res(r)));
const wait = (ms)=>new Promise(r=>setTimeout(r,ms));
const A = await conn(); A.emit("hello",{name:"H",avatar:"cat"});
const cr = await emit(A,"room:create",null);
const B = await conn(); B.emit("hello",{name:"G",avatar:"fox"});
await emit(B,"room:join",{code:cr.code});
A.emit("round:load",{wheel:{ls:["ق","ع","ر","ی","و"],words:[]}});
await wait(300);
B.emit("word:claim",{word:"قعر"});
await wait(300);
B.disconnect(); await wait(300);
const B2 = await conn(); B2.emit("hello",{name:"G",avatar:"fox"});
const stPromise = new Promise(res=>B2.on("room:state",(s)=>res(s)));
const rj = await emit(B2,"room:join",{code:cr.code});
const st = await Promise.race([stPromise, wait(1500).then(()=>null)]);
const g = st?.players?.find(p=>p.name==="G");
console.log("rejoin:", JSON.stringify(rj), "| G score:", g?.score, "| phase:", st?.phase);
A.close(); B2.close(); process.exit(0);
